id: A7E278DE4
title: The Prayer to Guru Rinpoche that Swiftly Removes Obstacles and Fulfills All
  Wishes
type: translation
pechas:
- IEF7FF57D
- IABDBBDDB
- I40921F0C
- I2562027E
source_metadata:
  languages:
  - en
  - fr
  - zh
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:48:01.227704
  last_modified_at: 2023-01-04 11:48:01.227714
  collections:
  - Dudjom Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  IEF7FF57D/3CD5: 74DD
  IABDBBDDB/C493: 74DD
  I40921F0C/4CDE: 74DD
  I2562027E/9AF4: 74DD
